### ISSUE TITLE
Thanks for opening! Can you offer the version that can be tested on GPU, such as Nvidia A100?

### ISSUE THREAD

**Issue by dinghongsong** [jannerm/ddpo#2]

**Comment by vinhkhuc** [comment]
@dinghongsong I've sent the PR #3 to support GPU. I tested it on A100. Could you give it a try?

**Comment by DevelopmentZheng** [comment]
> 

你好是不是你仓库里面的版本 就支持GPU了

**Comment by DevelopmentZheng** [comment]
@vinhkhuc  是不是你仓库里面的就支持GPU了

**Comment by kvablack** [comment]
Hi all, sorry for being so unresponsive --- this repository is pulled directly from our research code, and was never really meant to be easy to use, especially not on GPUs. I've recently been working on a PyTorch + LoRA version that will make it possible to use DDPO not only on GPUs, but even on small GPUs with <10Gb of VRAM. I'm almost done now and should be releasing very soon, so keep an eye out!

**Comment by kvablack** [comment]
Hey everyone, I'm going to close this issue as I would recommend moving over to the PyTorch version that's designed for GPUs [here](https://github.com/kvablack/ddpo-pytorch).
