### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by chaojiewang94** [jannerm/ddpo#5]
Have you released the dataset or how to download the datasets, thanks

**Comment by chaojiewang94** [comment]
should I modify the bucket = "gs://my_bucket" in use.py ?

**Comment by chaojiewang94** [comment]
the dataset is generated by python sample.py

**Comment by jannerm** [comment]
Yes, there is no static dataset; new data is sampled from the model on-the-fly during finetuning (in [sample.py](https://github.com/jannerm/ddpo/blob/main/pipeline/sample.py) for RWR variants and [policy_gradient.py](https://github.com/jannerm/ddpo/blob/main/pipeline/policy_gradient.py) for DDPO variants).

As for the bucket path, all of the samples and checkpoints are saved to the GCP bucket specified [on this line](https://github.com/jannerm/ddpo/blob/main/config/user.py#L1).
