### ISSUE TITLE
About prompt for Image-Text Alignment

### ISSUE THREAD

**Issue by chaojiewang94** [jannerm/ddpo#7]
I wonder which kind of prompt you used to generate images, which will be feeded into LLava to measure the reward of image-text alignment?

Is it the same as those used for other reward functions, like JEPG, or Aesthetic?

**Comment by jannerm** [comment]
The relevant fields in the config are `prompt_fn` and `prompt_kwargs`. For example, for the [`llava_bertscore` task](https://github.com/jannerm/ddpo/blob/main/config/base.py#L252-L256), it calls the [`nouns_activities`](https://github.com/jannerm/ddpo/blob/main/ddpo/training/prompts.py#L177-L184) prompt function with [`common_animals.txt`](https://github.com/jannerm/ddpo/blob/main/assets/common_animals.txt) and [`activities_v0.txt`](https://github.com/jannerm/ddpo/blob/main/assets/activities_v0.txt) as arguments.

**Comment by chaojiewang94** [comment]
Understand, thx
